const webChatEn = {
  title: 'Web Chat',
  newChat: 'New Chat',
  history: 'History',
  settings: 'Settings',
  send: 'Send',
  inputPlaceholder: 'Type a message...',
  thinking: 'Thinking...',
  suggestedQuestions: 'Suggested Questions',
  clearChat: 'Clear Chat',
  exportChat: 'Export Chat',
  noHistory: 'No history yet',
  welcomeMessage: 'Hello! I am an AI assistant. How can I help you today?',
  apiSettings: 'API Settings',
  provider: 'Provider',
  apiKey: 'API Key',
  baseUrl: 'Base URL',
  model: 'Model',
  temperature: 'Temperature',
  maxTokens: 'Max Tokens',
  systemPrompt: 'System Prompt',
  customHeaders: 'Custom Headers',
  customHeadersPlaceholder: 'Key: Value\nOne per line',
  testConnection: 'Test Connection',
  testing: 'Testing...',
  testSuccess: 'Connection successful',
  testFailed: 'Connection failed',
  save: 'Save',
  cancel: 'Cancel',
  delete: 'Delete',
  rename: 'Rename',
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  deepseek: 'DeepSeek',
  minimax: 'MiniMax',
  custom: 'Custom / OpenAI Compatible',
  apiKeyRequired: 'Please enter API key',
  configSaved: 'Configuration saved',
};

export default webChatEn;
