export const DESKTOP_STORAGE_APP_ID_TOKEN = '__DESKTOP_APP_ID__';
export const DESKTOP_STORAGE_LOCAL_SEED_TOKEN = '__DESKTOP_STORAGE_SEED_B64__';
export const DESKTOP_STORAGE_SESSION_SEED_TOKEN = '__DESKTOP_SESSION_SEED_B64__';
