const webChatZh = {
  title: '网页对话',
  newChat: '新对话',
  history: '历史记录',
  settings: '设置',
  send: '发送',
  inputPlaceholder: '输入消息...',
  thinking: '思考中...',
  suggestedQuestions: '推荐问题',
  clearChat: '清空对话',
  exportChat: '导出对话',
  noHistory: '暂无历史记录',
  welcomeMessage: '你好！我是 AI 助手，有什么可以帮助你的吗？',
  apiSettings: 'API 设置',
  provider: '提供商',
  apiKey: 'API 密钥',
  baseUrl: '基础地址',
  model: '模型',
  temperature: '温度',
  maxTokens: '最大令牌数',
  systemPrompt: '系统提示词',
  customHeaders: '自定义请求头',
  customHeadersPlaceholder: 'Key: Value\n每行一个',
  testConnection: '测试连接',
  testing: '测试中...',
  testSuccess: '连接成功',
  testFailed: '连接失败',
  save: '保存',
  cancel: '取消',
  delete: '删除',
  rename: '重命名',
  openai: 'OpenAI',
  anthropic: 'Anthropic',
  deepseek: 'DeepSeek',
  minimax: 'MiniMax',
  custom: '自定义 / OpenAI 兼容',
  apiKeyRequired: '请输入 API 密钥',
  configSaved: '配置已保存',
};

export default webChatZh;
